### ISSUE TITLE
404 NOT FOUND & 500 INTERNAL SERVER ERROR

### ISSUE THREAD

**Issue by coolguruji** [jclerc/xmusic#2]
Hi,

I saw your script i tried to install it on my centos operation system via command line.
When i tried to access it on my website i am getting following errors.

URL1: http://xmusic.download3gps.xyz/web/

Not Found

The requested URL /index.php was not found on this server.

Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.

URL2: http://xmusic.download3gps.xyz/web/index.php

Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at webmaster@xmusic.download3gps.xyz to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.

Additionally, a 500 Internal Server Error error was encountered while trying to use an ErrorDocument to handle the request.

I can see following folders and files in the home directory of my subdomain
.git
app
src
vendor
web
.gitignore
composer.json
composer.lock
README.md

Can you help me?

Thanks

**Comment by jclerc** [comment]
For 404 not found:
- Please check that you have the [`web/.htaccess`](https://github.com/JClerc/XMusic/blob/master/web/.htaccess) file
- Ensure that Apache is enabled on your web hosting

For 500 internal error: you need a production config but it is not defined by default. So you just need to:
1. Delete `app/config/production.php` file
2. Duplicate `app/config/development.php` file
3. Copy new file to `app/config/production.php`
