### ISSUE TITLE
Fatal error: Class 'Model\CacheServiceProvider' not found in /var/www/html/XMusic/app/bootstrap.php on line 64

### ISSUE THREAD

**Issue by cyber-cliff** [jclerc/xmusic#3]
after creating the production.php i got that error.
pls help.

**Comment by jclerc** [comment]
Please ensure that every file is correctly uploaded on your web hosting.
And which environment are you using? (PHP version, OS platform, ...)

**Comment by cyber-cliff** [comment]
Im using one of my VPS installed centos 7.

PHP VERSION
```
PHP 5.6.30 (cli) (built: Jan 19 2017 22:31:39) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
```

APACHE VERSION
`Server version: Apache/2.4.6 (CentOS)`

thanks,

**Comment by cyber-cliff** [comment]
I am also using the root user to config.

**Comment by cyber-cliff** [comment]
Can you help me pls...

**Comment by jclerc** [comment]
Delete all project files, then clone it again and checkout on #4 before installing it.

So:
```
git clone https://github.com/JClerc/XMusic.git
cd XMusic
git checkout fix/1-filename-case
composer install
```

Then run your web server on `web/` directory.

**Comment by cyber-cliff** [comment]
Yes thanks for that fix. It is running now, but i am getting another error on page saying...

`Warning: DateTime::createFromFormat(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /var/www/html/XMusic/vendor/symfony/http-foundation/Response.php on line 333`

Also when i on TRACKS or ARTIST OR ALBUMS i am getting a 404 not found. I checked the .htaccess file was there.

Here's my demo site. http://64.137.160.2

Thanks again,

**Comment by cyber-cliff** [comment]
Ok i just fix the Warning: DateTime::createFromFormat():

My only problem now is the 404 NOT FOUND.

**Comment by jclerc** [comment]
It's weird, the `.htaccess` file seems to be ignored.

I think it may be an issue with your Apache configuration, are you sure htaccess file are enabled?
Maybe take a look at this thread: https://askubuntu.com/questions/429869/is-this-a-correct-way-to-enable-htaccess-in-apache-2-4-7-on-ubuntu-12-04

If it is still not fixed, please open a new issue.
