### ISSUE TITLE
No Search Option.

### ISSUE THREAD

**Issue by cyber-cliff** [jclerc/xmusic#5]
Hi,

I just fix the 404 not found. And it is working now. But i face another problem. When i go to /tracks, /artists and /albums it doesnt have any search option.

Demo: http://64.137.160.2

**Comment by cyber-cliff** [comment]
Also i just tried your demo url but it is not working anymore. No results found.

**Comment by jclerc** [comment]
You have an error, check the source code of your page.
`view-source:http://64.137.160.2/tracks/` if you use Chrome.

It is the following:
`Fatal error:  Class 'DOMDocument' not found in /var/www/html/XMusic/vendor/symfony/config/Util/XmlUtils.php on line 52`

And should be solved by doing the following:
```sh
yum install php-xml
systemctl restart httpd.service
```

Btw, it works for me on my [website](https://xmusic.jclerc.com/tracks/) ([screen](https://i.imgur.com/76joHOz.png)).

**Comment by cyber-cliff** [comment]
Yes your site search area is working but no result will be displayed.

**Comment by cyber-cliff** [comment]
Please fix, no results found after searching. I tried your site too not working.


Thanks,

**Comment by dorian-delorme** [comment]
Please fix, i can't download my music by myself. I'm lost. Please come back !

**Comment by cyber-cliff** [comment]
Please help us to fix this bro..

**Comment by cyber-cliff** [comment]
where are you bro? please reply..

**Comment by cyber-cliff** [comment]
This dead?

**Comment by dorian-delorme** [comment]
It's sad to see people like him. We relied on him and he just left us unarmed against this hard world of music downloading. I clearly can't do it by myself. xoxo

**Comment by cyber-cliff** [comment]
Yeah me too, i cant fix it too.

**Comment by jclerc** [comment]
Spotify updated their API for searching an item (artist/track/...). It now requires a token, so the code have to be updated. I won't do it, this repo is not maintained anymore, but pull requests are welcomed!

See more here: [https://developer.spotify.com/web-api/search-item/](https://developer.spotify.com/web-api/search-item/)
